version: 2

plugins:
  duplication:
    enabled: true
    exclude_patters:
      - src/components/**/*.test.ts

exclude_patters:
  - src/database/*
  - build/**/*
  - coverage/**
  - node_modules/**/*
  - .editorconfig