version: '3.8'
services:
  redis:
    image: redis
    container_name: api_jwt_redis
    networks:
      - network
  postgres:
    image: postgres:12.9
    container_name: api_jwt_postgres
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=api_jwt_dev
    networks:
      - network
    depends_on:
      - redis
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
  api:
    image: eduahcb/api_jwt
    container_name: api
    expose:
      - 8080
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=staging
      - PORT=8080
      - TYPEORM_CONNECTION=postgres
      - TYPEORM_HOST=postgres
      - TYPEORM_PORT=5432
      - TYPEORM_USERNAME=postgres
      - TYPEORM_PASSWORD=123
      - TYPEORM_DATABASE=api_jwt_dev
      - REDIS_HOST=api_jwt_redis
      - TYPEORM_MIGRATIONS=build/database/migrations/*.js
      - TYPEORM_ENTITIES=build/components/**/*.entity.js
    entrypoint: ["/bin/sh", "./development.sh"]
    # entrypoint: ["ls", "-la", "build"]
    networks:
      - network
    depends_on:
      postgres:
        condition: service_healthy
networks:
  network:
    name: api_network
    driver: bridge