version: 2.1
orbs: 
  node: circleci/node@5.0.0
jobs:
  install-node:
    docker:
      - image: 'cimg/node:16.4.0'
    steps:
      - checkout
      - node/install:
          install-yarn: true
      - run: node --version
      - node/install-packages:
          pkg-manager: yarn
  
  install-postgres:
    docker:
      - image: 'cimg/postgres:12.0'
    steps:
      - checkout
      - run: sudo apt-get update
  eslint:
    executor:
      name: node/default
      tag: '16.4.0'
    steps:
      - checkout
      - run:
          command: yarn lint
          name: RUN ESLINT
  tests:
    executor:
      name: node/default
      tag: '16.4.0'
    steps:
      - checkout
      - run:
          command: yarn test
          name: RUN TESTS  
workflows:
  ci:
    jobs:
      - install-node
      - install-postgres
      - eslint