version: 2.1

aliases:
  - &restore-yarn-cache
    name: Restore yarnpkg cache
    key: v5-yarn-cache 

  - &restore-node-modules-cache
    name: Restore node_modules
    key: yarn-packages-{{ checksum "yarn.lock" }}
  
  - &save-node-modules-cache
    name: Save node_modules cache
    key: yarn-packages-{{ checksum "yarn.lock" }}
    paths:
      - node_modules

  - &save-yarn-cache
    name: Save yarnpkg cache
    key: v5-yarn-cache
    paths:
      - .cache/yarn 

  - &persist-workspace
    root: "api_jwt"
    paths:
      - ".eslintrc.json"
      - ".prettierrc"
      - "jest.config.ts"
      - "package.json"
      - "tsconfig.json"
      - "yarn.lock"
      - "tmp/*"


defaults: &defaults
  docker:
    - image: 'cimg/node:16.4.0'
    - image: 'cimg/postgres:12.9'
  working_directory: ~/workspace

jobs:
  build_packages:
    <<: *defaults

    steps:
      - checkout
      - restore_cache: *restore-node-modules-cache
      - restore_cache: *restore-yarn-cache

      - run:
          name: show the path before
          command: pwd
      
      - run:
          name: create api_jwt 
          command: mkdir api_jwt
        
      - run:
          name: show directories
          command: ls

      - run:
          name: got o api_jwt
          command: cd api_jwt
          
      - run:
          name: show the path after
          command: pwd

      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile --cache-folder ~/.cache/yarn
      
      - save_cache: *save-node-modules-cache
      - save_cache: *save-yarn-cache
      - persist_to_workspace: *persist-workspace

  eslint:

    <<: *defaults


    steps:
      - attach_workspace:
          at: ~/workspace/api_jwt
          
      - checkout
      - run:
          command: yarn lint
          name: RUN ESLINT

workflows:
  ci:
    jobs:
      - build_packages
      - eslint:
          requires:
            - build_packages