version: 2.1
orbs: 
  node: circleci/node@5.0.0
jobs:
  development:
    docker:
      - image: 'cimg/node:16.4.0'
      - image: 'cimg/postgres:12.9'
    steps:
      - checkout
      - node/install:
          install-yarn: true
      - run: node --version
      - node/install-packages:
          pkg-manager: yarn
  eslint:
    executor:
      name: node/default
      tag: '16.4.0'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn lint
          name: RUN ESLINT
  tests:
    executor:
      name: node/default
      tag: '16.4.0'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn test
          name: RUN TESTS  
workflows:
  ci:
    jobs:
      - development
      - eslint