version: 2.1

aliases:

  - &restore-yarn-cache:
    name: Restore yarnpkg cache
    keys:
      - yarn-packages-{{ checksum "yarn.lock" }}


  - &restore-node-modules-cache:
    name: Restore node_modules
    keys:
      - yarn-packages-{{ checksum "yarn.lock" }}

  - &save-node-modules-cache:
    name: Save node_modules cache
    paths:
      - node_modules

  - &save-yarn-cache
    name: Save yarnpkg cache
    key: yarn-packages-{{ checksum "yarn.lock" }}
    paths:
      - ~/.cache/yarn

defaults: &defaults
  docker:
    - image: 'cimg/node:16.4.0'
    - image: 'cimg/postgres:12.9'

jobs:
  build_packages:
    <<: *defaults

    steps:
      - checkout

      - restore_cache: *restore-node-modules-cache
      - restore_cache: *restore-yarn-cache

      - node/install:
        install-yarn: true
      - run: node --version
      - node/install-packages:
          pkg-manager: yarn
      - save_cache: *save-node-modules-cache
      - save_cache: *save-yarn-cache


  eslint:

    <<: *defaults

    steps:
      - checkout
      - run:
          command: yarn lint
          name: RUN ESLINT

workflows:
  ci:
    jobs:
      - development
      - eslint:
          requires:
            - development