version: 2.1

aliases:
  - &restore-yarn-cache
    name: Restore yarnpkg cache
    key: yarn-packages-{{ checksum "yarn.lock" }}

  - &restore-node-modules-cache
    name: Restore node_modules
    key: yarn-packages-{{ checksum "yarn.lock" }}
  
  - &save-node-modules-cache
    name: Save node_modules cache
    key: yarn-packages-{{ checum "yarn.lock" }}
    paths:
      - node_modules

  - &save-yarn-cache
    name: Save yarnpkg cache
    key: yarn-packages-{{ checksum "yarn.lock" }}
    paths:
      - ~/.cache/yarn
      
defaults: &defaults
  docker:
    - image: 'cimg/node:16.4.0'
    - image: 'cimg/postgres:12.9'

jobs:
  build_packages:
    <<: *defaults

    steps:
      - checkout
      - restore_cache: *restore-node-modules-cache
      - restore_cache: *restore-yarn-cache

      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile --cache-folder ~/.cache/yarn

      - save_cache: *save-node-modules-cache
      - save_cache: *save-yarn-cache

  eslint:

    <<: *defaults

    steps:
      - checkout
      - run:
          command: yarn lint
          name: RUN ESLINT

workflows:
  ci:
    jobs:
      - build_packages
      - eslint:
          requires:
            - build_packages